#version: '3.9'
services:
    dvwa:
        image: vulnerables/web-dvwa
        container_name: dvwa
        networks:
            - hacknet
        ports:
            - "80:80"
        volumes:
            - dvwa-data:/var/www/html
            - dvwa-mysql:/var/lib/mysql
        environment:
            MYSQL_USER: "dvwa"
            MYSQL_PASSWORD: "dvwa"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "dvwa"
            
    kali:
        image: kalilinux/kali-rolling
        container_name: kali
        networks:
            - hacknet
        volumes:
            - kali-data:/root/results 
        tty: true
        stdin_open: true     
networks:
    hacknet:
        driver: bridge
volumes:
    dvwa-data:
    dvwa-mysql:
    kali-data:
    