version: '3.9'

services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    networks:
      - hacknet
    volumes:
      - dvwa-data:/var/lib/mysql
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dvwa"
      MYSQL_USER: "dvwa"
      MYSQL_PASSWORD: "dvwa"

  kali:
    image: kalilinux/kali-rolling:latest
    container_name: kali
    networks:
      - hacknet
    volumes:
      - kali-data:/root/data
    stdin_open: true
    tty: true

networks:
  hacknet:
    driver: bridge

volumes:
  dvwa-data:
  kali-data: